# Generated by Django 2.2.7 on 2020-03-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('admin_phone', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='管理员电话')),
                ('admin_picture', models.ImageField(default='administrators/default_admin.png', upload_to='administrators', verbose_name='管理员头像')),
                ('admin_name', models.CharField(max_length=24, verbose_name='管理员姓名')),
                ('admin_password', models.CharField(max_length=64, verbose_name='管理员密码')),
                ('admin_email', models.EmailField(max_length=32, verbose_name='管理员邮箱')),
                ('admin_created_time', models.DateTimeField(auto_now_add=True, verbose_name='管理员创建时间')),
                ('admin_updated_time', models.DateTimeField(auto_now=True, verbose_name='管理员更新时间')),
            ],
            options={
                'verbose_name': '管理员表',
                'verbose_name_plural': '管理员表',
                'db_table': 'management',
            },
        ),
        migrations.CreateModel(
            name='ShopMassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=32, verbose_name='店家名字')),
                ('shop_site', models.CharField(max_length=100, null=True, verbose_name='店家位置信息')),
                ('shop_longitude', models.FloatField(verbose_name='位置经度')),
                ('shop_latitude', models.FloatField(verbose_name='位置纬度')),
            ],
            options={
                'verbose_name': '店家信息表',
                'verbose_name_plural': '店家信息表',
                'db_table': 'shopmassage',
            },
        ),
    ]
