# Generated by Django 2.2.7 on 2020-03-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercode',
            options={'verbose_name': '验证码表', 'verbose_name_plural': '验证码表'},
        ),
        migrations.AlterModelTable(
            name='usercode',
            table='user_code',
        ),
    ]
