# Generated by Django 2.2.7 on 2020-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200309_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='user_code',
            field=models.CharField(max_length=6, verbose_name='用户验证码'),
        ),
    ]
