# Generated by Django 2.2.7 on 2020-03-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('desk_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='桌号')),
                ('desk_isActive', models.BooleanField(default=True, verbose_name='是否空闲')),
                ('desk_user_number', models.IntegerField(verbose_name='桌台人数')),
                ('desk_password', models.CharField(max_length=64, verbose_name='桌台密码')),
            ],
            options={
                'verbose_name': '桌台信息表',
                'verbose_name_plural': '桌台信息表',
                'db_table': 'desk',
            },
        ),
        migrations.CreateModel(
            name='DeskUrl',
            fields=[
                ('desk', models.IntegerField(primary_key=True, serialize=False, verbose_name='桌号')),
                ('desk_url', models.CharField(max_length=100, verbose_name='桌台链接')),
                ('desk_code', models.ImageField(upload_to='code', verbose_name='桌台二维码')),
            ],
            options={
                'verbose_name': '桌台二维码表',
                'verbose_name_plural': '桌台二维码表',
                'db_table': 'desk_code',
            },
        ),
        migrations.CreateModel(
            name='Green',
            fields=[
                ('green_number', models.IntegerField(default=600001, primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('green_name', models.CharField(max_length=30, verbose_name='菜品名称')),
                ('green_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='菜品价格')),
                ('green_picture', models.ImageField(default='menu/default_menu.png', upload_to='menu', verbose_name='商品图片')),
                ('green_isActive', models.BooleanField(default=True, verbose_name='是否上架')),
                ('green_created_time', models.DateTimeField(auto_now_add=True, verbose_name='菜品创建时间')),
                ('green_updated_time', models.DateTimeField(auto_now=True, verbose_name='菜品更新时间')),
                ('green_label', models.CharField(max_length=33, null=True, verbose_name='菜品标签')),
                ('green_recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '菜品信息表',
                'verbose_name_plural': '菜品信息表',
                'db_table': 'green',
            },
        ),
        migrations.CreateModel(
            name='Greens',
            fields=[
                ('greens_number', models.IntegerField(default=500001, primary_key=True, serialize=False, verbose_name='类别号')),
                ('greens_name', models.CharField(max_length=30, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '菜品类别信息表',
                'verbose_name_plural': '菜品类别信息表',
                'db_table': 'greens',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_type', models.CharField(choices=[('R', '预订'), ('A', '实时')], max_length=2, verbose_name='订单类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单下单时间')),
                ('take_time', models.DateTimeField(verbose_name='订单生效时间')),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='订单总价')),
                ('user_order_isActive', models.BooleanField(default=False, verbose_name='用户是否删除')),
                ('admin_order_isActive', models.BooleanField(default=False, verbose_name='管理员是否删除')),
                ('order_state', models.CharField(choices=[('P', '进行中'), ('R', '预订中'), ('O', '完成'), ('S', '取消'), ('L', '失效')], default='P', max_length=2)),
                ('order_user_number', models.IntegerField(verbose_name='订单人数')),
                ('customer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='订单所属顾客')),
                ('order_desk', models.ManyToManyField(blank=True, default=None, to='message.Desk', verbose_name='所属桌台')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11, verbose_name='用户ID')),
                ('green_number', models.IntegerField(default=1)),
                ('cart_green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Green', verbose_name='购物车中的菜品')),
            ],
            options={
                'db_table': 'shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='菜品数量')),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Green', verbose_name='订单中的菜品')),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Order', verbose_name='订单详细信息')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 'orderdata',
            },
        ),
        migrations.AddField(
            model_name='green',
            name='green_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Greens', verbose_name='所属菜品类别'),
        ),
    ]
